-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject is
port (
    tracks_0_V_V_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    layer102_out_0_V_V_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    tracks_0_V_V_TVALID : IN STD_LOGIC;
    tracks_0_V_V_TREADY : OUT STD_LOGIC;
    layer102_out_0_V_V_TVALID : OUT STD_LOGIC;
    layer102_out_0_V_V_TREADY : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of myproject is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "myproject,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=1.464000,HLS_SYN_LAT=345,HLS_SYN_TPT=346,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=26,HLS_SYN_LUT=209,HLS_VERSION=2019_2}";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_start : STD_LOGIC;
    signal mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_done : STD_LOGIC;
    signal mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_continue : STD_LOGIC;
    signal mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_idle : STD_LOGIC;
    signal mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_ready : STD_LOGIC;
    signal mask_track_switch_ap_fixed_ap_fixed_config5_U0_data_V_V_TREADY : STD_LOGIC;
    signal mask_track_switch_ap_fixed_ap_fixed_config5_U0_res_V_V_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal mask_track_switch_ap_fixed_ap_fixed_config5_U0_res_V_V_TVALID : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal mask_track_switch_ap_fixed_ap_fixed_config5_U0_start_full_n : STD_LOGIC;
    signal mask_track_switch_ap_fixed_ap_fixed_config5_U0_start_write : STD_LOGIC;

    component mask_track_switch_ap_fixed_ap_fixed_config5_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_V_V_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        data_V_V_TVALID : IN STD_LOGIC;
        data_V_V_TREADY : OUT STD_LOGIC;
        res_V_V_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        res_V_V_TVALID : OUT STD_LOGIC;
        res_V_V_TREADY : IN STD_LOGIC );
    end component;



begin
    mask_track_switch_ap_fixed_ap_fixed_config5_U0 : component mask_track_switch_ap_fixed_ap_fixed_config5_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_start,
        ap_done => mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_done,
        ap_continue => mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_continue,
        ap_idle => mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_idle,
        ap_ready => mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_ready,
        data_V_V_TDATA => tracks_0_V_V_TDATA,
        data_V_V_TVALID => tracks_0_V_V_TVALID,
        data_V_V_TREADY => mask_track_switch_ap_fixed_ap_fixed_config5_U0_data_V_V_TREADY,
        res_V_V_TDATA => mask_track_switch_ap_fixed_ap_fixed_config5_U0_res_V_V_TDATA,
        res_V_V_TVALID => mask_track_switch_ap_fixed_ap_fixed_config5_U0_res_V_V_TVALID,
        res_V_V_TREADY => layer102_out_0_V_V_TREADY);




    ap_done <= mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_done;
    ap_idle <= mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_idle;
    ap_ready <= mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_continue <= ap_const_logic_1;
    ap_sync_done <= mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_done;
    ap_sync_ready <= mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_ready;
    layer102_out_0_V_V_TDATA <= mask_track_switch_ap_fixed_ap_fixed_config5_U0_res_V_V_TDATA;
    layer102_out_0_V_V_TVALID <= mask_track_switch_ap_fixed_ap_fixed_config5_U0_res_V_V_TVALID;
    mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_continue <= ap_const_logic_1;
    mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_start <= ap_start;
    mask_track_switch_ap_fixed_ap_fixed_config5_U0_start_full_n <= ap_const_logic_1;
    mask_track_switch_ap_fixed_ap_fixed_config5_U0_start_write <= ap_const_logic_0;
    tracks_0_V_V_TREADY <= mask_track_switch_ap_fixed_ap_fixed_config5_U0_data_V_V_TREADY;
end behav;
