// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=1.464000,HLS_SYN_LAT=345,HLS_SYN_TPT=346,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=26,HLS_SYN_LUT=209,HLS_VERSION=2019_2}" *)

module myproject (
        tracks_0_V_V_TDATA,
        layer102_out_0_V_V_TDATA,
        ap_clk,
        ap_rst_n,
        tracks_0_V_V_TVALID,
        tracks_0_V_V_TREADY,
        layer102_out_0_V_V_TVALID,
        layer102_out_0_V_V_TREADY,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input  [31:0] tracks_0_V_V_TDATA;
output  [31:0] layer102_out_0_V_V_TDATA;
input   ap_clk;
input   ap_rst_n;
input   tracks_0_V_V_TVALID;
output   tracks_0_V_V_TREADY;
output   layer102_out_0_V_V_TVALID;
input   layer102_out_0_V_V_TREADY;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_start;
wire    mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_done;
wire    mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_continue;
wire    mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_idle;
wire    mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_ready;
wire    mask_track_switch_ap_fixed_ap_fixed_config5_U0_data_V_V_TREADY;
wire   [31:0] mask_track_switch_ap_fixed_ap_fixed_config5_U0_res_V_V_TDATA;
wire    mask_track_switch_ap_fixed_ap_fixed_config5_U0_res_V_V_TVALID;
wire    ap_sync_continue;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    mask_track_switch_ap_fixed_ap_fixed_config5_U0_start_full_n;
wire    mask_track_switch_ap_fixed_ap_fixed_config5_U0_start_write;

mask_track_switch_ap_fixed_ap_fixed_config5_s mask_track_switch_ap_fixed_ap_fixed_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_start),
    .ap_done(mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_done),
    .ap_continue(mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_continue),
    .ap_idle(mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_idle),
    .ap_ready(mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_ready),
    .data_V_V_TDATA(tracks_0_V_V_TDATA),
    .data_V_V_TVALID(tracks_0_V_V_TVALID),
    .data_V_V_TREADY(mask_track_switch_ap_fixed_ap_fixed_config5_U0_data_V_V_TREADY),
    .res_V_V_TDATA(mask_track_switch_ap_fixed_ap_fixed_config5_U0_res_V_V_TDATA),
    .res_V_V_TVALID(mask_track_switch_ap_fixed_ap_fixed_config5_U0_res_V_V_TVALID),
    .res_V_V_TREADY(layer102_out_0_V_V_TREADY)
);

assign ap_done = mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_done;

assign ap_idle = mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_idle;

assign ap_ready = mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_done;

assign ap_sync_ready = mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_ready;

assign layer102_out_0_V_V_TDATA = mask_track_switch_ap_fixed_ap_fixed_config5_U0_res_V_V_TDATA;

assign layer102_out_0_V_V_TVALID = mask_track_switch_ap_fixed_ap_fixed_config5_U0_res_V_V_TVALID;

assign mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_continue = 1'b1;

assign mask_track_switch_ap_fixed_ap_fixed_config5_U0_ap_start = ap_start;

assign mask_track_switch_ap_fixed_ap_fixed_config5_U0_start_full_n = 1'b1;

assign mask_track_switch_ap_fixed_ap_fixed_config5_U0_start_write = 1'b0;

assign tracks_0_V_V_TREADY = mask_track_switch_ap_fixed_ap_fixed_config5_U0_data_V_V_TREADY;

endmodule //myproject
